#esercizio 6: Creare una classe Animale con un attributo di classe numero_animali che tiene traccia del numero di animali creati. La classe deve avere un metodo di classe quanti_animali() che restituisce il numero di animali creati. Ogni volta che viene creata un'istanza della classe Animale, il contatore numero_animali deve essere incrementato di 1.    
# La classe Animale rappresenta un animale con un nome e una specie. L'attribut di classe numero_animali tiene traccia del numero totale di animali creati. Il metodo di classe quanti_animali() restituisce il numero di animali creati, accedendo all'attributo di classe numero_animali. Ogni volta che viene creata un'istanza della classe Animale, il costruttore __init__ incrementa il contatore numero_animali di 1, assicurando che il conteggio sia aggiornato correttamente ogni volta che viene creato un nuovo animale. Infine, vengono create alcune istanze della classe Animale e viene chiamato il metodo quanti_animali() per mostrare il numero totale di animali creati.    
# Output: Numero di animali creati: 3   


class Animale: # La classe Animale rappresenta un animale con un nome e una specie. L'attributo di classe numero_animali tiene traccia del numero totale di animali creati. Il metodo di classe quanti_animali() restituisce il numero di animali creati, accedendo all'attributo di classe numero_animali. Ogni volta che viene creata un'istanza della classe Animale, il costruttore __init__ incrementa il contatore numero_animali di 1, assicurando che il conteggio sia aggiornato correttamente ogni volta che viene creato un nuovo animale. Infine, vengono create alcune istanze della classe Animale e viene chiamato il metodo quanti_animali() per mostrare il numero totale di animali creati.   

    numero_animali = 0

    def __init__(self, nome, specie): # Il metodo __init__ è il costruttore della classe, che accetta due argomenti: nome e specie, e li assegna agli attributi dell'istanza. Gli attributi self.nome e self.specie sono variabili di istanza che vengono create per ogni istanza della classe Animale. Questi attributi memorizzano il nome e la specie dell'animale, rispettivamente. L'uso di self permette di accedere a questi attributi all'interno della classe e di differenziarli da eventuali variabili locali o globali con lo stesso nome. Inoltre, all'interno del costruttore, viene incrementato l'attributo di classe numero_animali di 1 ogni volta che viene creata una nuova istanza della classe Animale, tenendo traccia del numero totale di animali creati.  
        self.nome = nome # L'attributo self.nome memorizza il nome dell'animale, che viene passato come argomento al costruttore. Ad esempio, quando si crea un'istanza della classe Animale con nome "Fido", l'attributo self.nome di quell'istanza conterrà la stringa "Fido". Questo attributo può essere utilizzato per accedere al nome dell'animale in altri metodi della classe o per visualizzarlo quando necessario.                                                           
        self.specie = specie # L'attributo self.specie memorizza la specie dell'animale, che viene passato come argomento al costruttore. Ad esempio, quando si crea un'istanza della classe Animale con specie "Cane", l'attributo self.specie di quell'istanza conterrà la stringa "Cane". Questo attributo può essere utilizzato per accedere alla specie dell'animale in altri metodi della classe o per visualizzarla quando necessario.
        Animale.numero_animali += 1 # All'interno del costruttore __init__, viene incrementato l'attributo di classe numero_animali di 1 ogni volta che viene creata una nuova istanza della classe Animale. Questo permette di tenere traccia del numero totale di animali creati. Ad esempio, se si creano tre istanze della classe Animale, il valore di Animale.numero_animali sarà 3, indicando che sono stati creati tre animali.

    @classmethod # Il decoratore @classmethod indica che il metodo è un metodo di classe, il che significa che accetta la classe stessa come primo argomento (convenzionalmente chiamato cls) invece di un'istanza della classe. I metodi di classe possono accedere e modificare gli attributi di classe, ma non possono accedere agli attributi di istanza. In questo caso, il metodo quanti_animali() è definito come un metodo di classe perché restituisce il numero totale di animali creati, che è memorizzato nell'attributo di classe numero_animali. Questo metodo può essere chiamato direttamente sulla classe Animale senza la necessità di creare un'istanza della classe, ad esempio, Animale.quanti_animali() restituirà il numero totale di animali creati.
    def quanti_animali(cls): # Il metodo quanti_animali() è un metodo di classe che restituisce il numero totale di animali creati, accedendo all'attributo di classe numero_animali. Poiché è un metodo di classe, accetta la classe stessa come primo argomento (convenzionalmente chiamato cls) invece di un'istanza della classe. All'interno del metodo, viene stampato il numero di animali creati utilizzando l'attributo di classe numero_animali. Ad esempio, se sono stati creati tre animali, chiamando Animale.quanti_animali() stamperà "Numero di animali creati: 3". Questo metodo consente di ottenere facilmente il conteggio totale degli animali creati senza dover accedere direttamente all'attributo di classe numero_animali.
        print(f"Numero di animali creati: {cls.numero_animali}")
        
        
animale1 = Animale("Fido", "Cane")
animale2 = Animale("Micio", "Gatto")
animale3 = Animale("Luna", "Coniglio")

Animale.quanti_animali() # Alla fine del codice, viene chiamato il metodo di classe quanti_animali() sulla classe Animale per mostrare il numero totale di animali creati. Poiché sono state create tre istanze della classe Animale (animale1, animale2 e animale3), il metodo quanti_animali() stamperà "Numero di animali creati: 3", indicando che sono stati creati tre animali.

